### ISSUE TITLE
Migrating Content does not preserve localised fields in Block Matrices

### ISSUE THREAD

**Issue by realmunk** [Firstborn/Craft-CMS-Migration-Manager#23] opened 2018-03-15 10:55 UTC
When performing content migration on an entry which contains a non-translatable top level matrix field, there's a loss of localised content for each field which has this property within the matrix block.

Each field seems to be overwritten by the latest imported locale.

Any idea on how to fix? I can provide an example if needed.

**Comment by fb-derrick-grigg** [comment] 2018-03-15 13:32
@realmunk some additional clarity would be helpful. Maybe a screen shot of the matrix setup.

**Comment by realmunk** [comment] 2018-03-15 13:55
I can add the migration file if further clarity is needed.

A screenshot of the Matrix Field setup is available here:

<img width="1435" alt="screen shot 2018-03-15 at 14 50 12" src="https://user-images.githubusercontent.com/2530427/37467327-3373aa00-2860-11e8-916e-82e1701f27f3.png">

**Comment by fb-derrick-grigg** [comment] 2018-03-15 13:58
And during the migration the 'key' and 'value' fields are being updated the with the last imported locale values not their specific locale values. Ie if there are three locales they all end up with the values of the final locale?

**Comment by realmunk** [comment] 2018-03-15 13:59
Yes, that's correct.

**Comment by fb-derrick-grigg** [comment] 2018-03-15 13:59
Ok, let me see what I can figure out.

**Comment by fb-derrick-grigg** [comment] 2018-03-21 11:28
@realmunk this has been fixed in release 1.0.8.8. Matrix and Supertable field were both affected by the issue with localized data when the top field was not translatable.

**Closed as completed by fb-derrick-grigg** 2018-03-21 11:28 UTC

**Comment by realmunk** [comment] 2018-03-21 13:19
Fantastic! <3

**Comment by webkp** [comment] 2018-07-24 14:41
I had the exact same problem today. It doesn't seem to be solved yet. I'm using 1.0.9.1.

Quickly looking at the code I think the translatable parameter is missing between here for Matrix:
https://github.com/Firstborn/Craft-CMS-Migration-Manager/blob/4bd0e8b9c3462719e2f0606074bff3820642fa50/migrationmanager/services/MigrationManager_FieldsService.php#L248-L249

and here for SuperTable :
https://github.com/Firstborn/Craft-CMS-Migration-Manager/blob/4bd0e8b9c3462719e2f0606074bff3820642fa50/migrationmanager/services/MigrationManager_FieldsService.php#L292-L293

I quickly changed that for Matrix to:
````
'required' => $blockField->required,
'translatable' => $blockField->translatable,
'type' => $blockField->type,
````
and the translatable parameter appeared in the json migration file.
But I don't know the extension well enough to know if other changes are necessary. 

BTW: It's already working with regular field types (non-matrix). This seems to be only an issue with Matrix and SuperTable fields.

**Comment by fb-derrick-grigg** [comment] 2018-07-24 16:01
@webkp I will run some tests to double check. The original issue was with content migrations, it looks like you are talking about field (setting) migrations, is that correct?

**Comment by webkp** [comment] 2018-07-24 16:11
You're right, of course. Sorry for the confusion. Yes my issue was related to field migrations.

Am 24. Juli 2018 18:01:39 MESZ schrieb Derrick Grigg <notifications@github.com>:

**Comment by fdeneux** [comment] 2018-10-05 14:08
I can confirm @webkp 's issue. Previously checked translatable checkboxes were lost when migrating a Matrix field's settings, causing the loss of its translations when re-saving an already existing block.
